/* ============================================================
   DATOS · Pokémon Unite
   Winrates/Pickrates/Banrates: uniteapi.dev (2026-09-20)
   Roles, builds e ítems: unite-db.com
   100 Pokémon · 286 builds · 133,492 partidas
============================================================ */
window.DraftSim = window.DraftSim || {};

window.DraftSim.SPRITE_URL = function(id){
  return 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/' + id + '.png';
};

window.DraftSim.POKEMON = [

  /* ============ ATTACKERS ============ */
  { n:"Armarouge", r:"Attacker", id:936, wr:50.9, pr:3.7, br:0.2,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Fire Shock", "moves":["Fire Spin", "Psyshock"],"items":["Shell Bell", "Curse Incense", "Drive Lens", "Eject Button"]},
      {"name":"Fire Charge", "moves":["Fire Spin", "Flame Charge"],"items":["Shell Bell", "Curse Incense", "Drive Lens", "Full Heal"]},
      {"name":"Armor Shock", "moves":["Armor Cannon", "Psyshock"],"items":["Drive Lens", "Wise Glasses", "Slick Spoon", "Eject Button"]}] },

  { n:"Chandelure", r:"Attacker", id:609, wr:49.8, pr:3.5, br:0.3,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Flame Geist", "moves":["Flamethrower", "Poltergeist"],"items":["Slick Spoon", "Curse Incense", "Drive Lens", "Eject Button"]},
      {"name":"Heat Prison", "moves":["Overheat", "Imprison"],"items":["Slick Spoon", "Curse Incense", "Drive Lens", "Eject Button"]},
      {"name":"Flame Prison", "moves":["Flamethrower", "Imprison"],"items":["Slick Spoon", "Curse Incense", "Drive Lens", "Eject Button"]},
      {"name":"Heat Geist", "moves":["Overheat", "Poltergeist"],"items":["Slick Spoon", "Curse Incense", "Drive Lens", "Eject Button"]}] },

  { n:"Cinderace", r:"Attacker", id:815, wr:50.2, pr:24, br:2.5,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Blazing Feint", "moves":["Blaze Kick", "Feint"],"items":["Scope Lens", "Muscle Band", "Rapid Fire Scarf", "Eject Button"]},
      {"name":"Pyro Feint", "moves":["Pyro Ball", "Feint"],"items":["Scope Lens", "Muscle Band", "Rapid Fire Scarf", "Eject Button"]},
      {"name":"Flame Kick", "moves":["Blaze Kick", "Flame Charge"],"items":["Scope Lens", "Muscle Band", "Rapid Fire Scarf", "Eject Button"]},
      {"name":"Pyro Charge", "moves":["Pyro Ball", "Flame Charge"],"items":["Scope Lens", "Muscle Band", "Rapid Fire Scarf", "Eject Button"]}] },

  { n:"Cramorant", r:"Attacker", id:845, wr:50.6, pr:4.3, br:0.2,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Dive Slash", "moves":["Air Slash", "Dive"],"items":["Energy Amplifier", "Drive Lens", "Shell Bell", "Eject Button"]},
      {"name":"Diveicane", "moves":["Hurricane", "Dive"],"items":["Energy Amplifier", "Drive Lens", "Shell Bell", "Eject Button"]},
      {"name":"Surficane", "moves":["Hurricane", "Surf"],"items":["Energy Amplifier", "Drive Lens", "Shell Bell", "Eject Button"]}] },

  { n:"Decidueye", r:"Attacker", id:724, wr:50.6, pr:29.7, br:6.6,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Shadow Shackle", "moves":["Spirit Shackle", "Shadow Sneak"],"items":["Muscle Band", "Accel Bracer", "Attack Weight", "Eject Button"]},
      {"name":"Razor Storm", "moves":["Razor Leaf", "Leaf Storm"],"items":["Muscle Band", "Scope Lens", "Rapid Fire Scarf", "Eject Button"]},
      {"name":"Shackle Storm", "moves":["Spirit Shackle", "Leaf Storm"],"items":["Muscle Band", "Accel Bracer", "Attack Weight", "Eject Button"]}] },

  { n:"Delphox", r:"Attacker", id:655, wr:49.6, pr:9, br:0.6,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Mystical Charge", "moves":["Mystical Fire", "Flame Charge"],"items":["Energy Amplifier", "Drive Lens", "Shell Bell", "Eject Button"]},
      {"name":"Blast Spin", "moves":["Fire Blast", "Fire Spin"],"items":["Energy Amplifier", "Drive Lens", "Shell Bell", "Eject Button"]},
      {"name":"Mystical Spin", "moves":["Mystical Fire", "Fire Spin"],"items":["Energy Amplifier", "Drive Lens", "Shell Bell", "Eject Button"]}] },

  { n:"Dragapult", r:"Attacker", id:887, wr:51.7, pr:15.3, br:6.5,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Shadow Force", "moves":["Phantom Force", "Shadow Ball"],"items":["Muscle Band", "Scope Lens", "Razor Claw", "Eject Button"]},
      {"name":"Double Dragon", "moves":["Dragon Dance", "Dragon Breath"],"items":["Muscle Band", "Scope Lens", "Charging Charm", "Full Heal"]}] },

  { n:"Duraludon", r:"Attacker", id:884, wr:53.5, pr:3.3, br:0.2,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Flash Tail", "moves":["Flash Cannon", "Dragon Tail"],"items":["Muscle Band", "Scope Lens", "Rapid Fire Scarf", "Full Heal"]},
      {"name":"Flash Rocks", "moves":["Flash Cannon", "Stealth Rock"],"items":["Muscle Band", "Scope Lens", "Rapid Fire Scarf", "Full Heal"]},
      {"name":"Dragon Rocks", "moves":["Dragon Pulse", "Stealth Rock"],"items":["Muscle Band", "Attack Weight", "Accel Bracer", "Eject Button"]}] },

  { n:"Espeon", r:"Attacker", id:196, wr:50.1, pr:24.6, br:1.6,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Shock Beam", "moves":["Psyshock", "Psybeam"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Stored Beam", "moves":["Stored Power", "Psybeam"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Shock Sight", "moves":["Psyshock", "Future Sight"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Stored Sight", "moves":["Stored Power", "Future Sight"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]}] },

  { n:"Gardevoir", r:"Attacker", id:282, wr:50.5, pr:10.6, br:0.7,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Psychic Shock", "moves":["Psyshock", "Psychic"],"items":["Drive Lens", "Wise Glasses", "Choice Specs", "Eject Button"]},
      {"name":"Future Moon", "moves":["Future Sight", "Moonblast"],"items":["Slick Spoon", "Drive Lens", "Wise Glasses", "Eject Button"]},
      {"name":"Psyblast", "moves":["Psyshock", "Moonblast"],"items":["Slick Spoon", "Drive Lens", "Wise Glasses", "Eject Button"]},
      {"name":"Future Psychic", "moves":["Future Sight", "Psychic"],"items":["Drive Lens", "Wise Glasses", "Choice Specs", "Eject Button"]}] },

  { n:"Glaceon", r:"Attacker", id:471, wr:48.7, pr:10.9, br:0.9,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Spear Shard", "moves":["Icicle Spear", "Ice Shard"],"items":["Wise Glasses", "Curse Incense", "Slick Spoon", "Eject Button"]},
      {"name":"Freeze Wind", "moves":["Icy Wind", "Freeze Dry"],"items":["Slick Spoon", "Drive Lens", "Shell Bell", "Eject Button"]},
      {"name":"Freeze Wind", "moves":["Icy Wind", "Freeze Dry"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]}] },

  { n:"Greninja", r:"Attacker", id:658, wr:51.6, pr:22.6, br:2.7,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Surf Screen", "moves":["Smokescreen", "Surf"],"items":["Muscle Band", "Scope Lens", "Charging Charm", "Eject Button"]},
      {"name":"Double Shuriken", "moves":["Double Team", "Water Shuriken"],"items":["Attack Weight", "Muscle Band", "Accel Bracer", "Eject Button"]},
      {"name":"Surf Screen (All-in)", "moves":["Smokescreen", "Surf"],"items":["Muscle Band", "Attack Weight", "Accel Bracer", "X Attack"]}] },

  { n:"Inteleon", r:"Attacker", id:818, wr:47.3, pr:6.3, br:0.2,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Snipe Stinger", "moves":["Fell Stinger", "Snipe Shot"],"items":["Choice Specs", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Acrobatics Liquidation", "moves":["Acrobatics", "Liquidation"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Liquidation Stinger", "moves":["Fell Stinger", "Liquidation"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]}] },

  { n:"Latios", r:"Attacker", id:381, wr:50.6, pr:21, br:16.6,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Dragon-kinesis", "moves":["Dragon Pulse", "Telekinesis"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Draco-kinesis", "moves":["Draco Meteor", "Telekinesis"],"items":["Slick Spoon", "Curse Incense", "Drive Lens", "Eject Button"]},
      {"name":"Draco Purge", "moves":["Draco Meteor", "Luster Purge"],"items":["Slick Spoon", "Curse Incense", "Drive Lens", "Eject Button"]}] },

  { n:"Mega Mewtwo Y", r:"Attacker", id:10044, wr:50.2, pr:16.2, br:7.4,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Items Only", "moves":["Confusion", "Barrier"],"items":["Mewtwonite Y", "Muscle Band", "Rapid Fire Scarf", "X Attack"]}] },

  { n:"Mew", r:"Attacker", id:151, wr:49.1, pr:11.1, br:1.9,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Items Only", "moves":[],"items":["Choice Specs", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Items Only", "moves":[],"items":["Exp Share", "Choice Specs", "Wise Glasses", "Eject Button"]}] },

  { n:"Miraidon", r:"Attacker", id:1008, wr:47.9, pr:3.6, br:0.2,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Thunder Beam", "moves":["Charge Beam", "Thunder"],"items":["Curse Incense", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Parabolic Drift", "moves":["Electro Drift", "Parabolic Charge"],"items":["Shell Bell", "Wise Glasses", "Drive Lens", "Eject Button"]}] },

  { n:"Ninetales", r:"Attacker", id:38, wr:49.8, pr:13.1, br:2.4,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Sheer Cold", "moves":["Avalanche", "Blizzard"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Dazzling Veil (no emblems)", "moves":["Dazzling Gleam", "Aurora Veil"],"items":["Slick Spoon", "Muscle Band", "Drive Lens", "Eject Button"]},
      {"name":"Dazzling Veil", "moves":["Dazzling Gleam", "Aurora Veil"],"items":["Rapid Fire Scarf", "Muscle Band", "Slick Spoon", "X Attack"]},
      {"name":"Dazzling Veil", "moves":["Dazzling Gleam", "Aurora Veil"],"items":["Muscle Band", "Slick Spoon", "Drive Lens", "Eject Button"]}] },

  { n:"Pikachu", r:"Attacker", id:25, wr:50.1, pr:23, br:9.5,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Full Thunder", "moves":["Thunder", "Thunderbolt"],"items":["Energy Amplifier", "Curse Incense", "Drive Lens", "Eject Button"]},
      {"name":"Electro Tackle", "moves":["Electro Ball", "Volt Tackle"],"items":["Energy Amplifier", "Slick Spoon", "Buddy Barrier", "Eject Button"]},
      {"name":"Thunder Tackle", "moves":["Thunder", "Volt Tackle"],"items":["Energy Amplifier", "Curse Incense", "Slick Spoon", "Eject Button"]},
      {"name":"Electro Bolt", "moves":["Electro Ball", "Thunderbolt"],"items":["Energy Amplifier", "Slick Spoon", "Shell Bell", "Eject Button"]}] },

  { n:"Raichu", r:"Attacker", id:26, wr:49.7, pr:11.8, br:3,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Electro Bolt", "moves":["Electro Ball", "Thunderbolt"],"items":["Wise Glasses", "Drive Lens", "Shell Bell", "Eject Button"]},
      {"name":"Stored Psychic", "moves":["Stored Power", "Psychic"],"items":["Wise Glasses", "Drive Lens", "Muscle Band", "Eject Button"]},
      {"name":"Stored Bolt", "moves":["Stored Power", "Thunderbolt"],"items":["Wise Glasses", "Drive Lens", "Muscle Band", "Eject Button"]}] },

  { n:"Reshiram", r:"Attacker", id:643, wr:49.7, pr:16.1, br:51.4,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Dragon Flare", "moves":["Dragon Dance", "Blue Flare"],"items":["Slick Spoon", "Drive Lens", "Energy Amplifier", "Eject Button"]}] },

  { n:"Skeledirge", r:"Attacker", id:911, wr:48.6, pr:7.9, br:0.7,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Hyper Snarl", "moves":["Hyper Voice", "Snarl"],"items":["Energy Amplifier", "Slick Spoon", "Drive Lens", "Eject Button"]}] },

  { n:"Sylveon", r:"Attacker", id:700, wr:50.1, pr:10.3, br:0.6,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Hyper Mind", "moves":["Hyper Voice", "Calm Mind"],"items":["Curse Incense", "Shell Bell", "Drive Lens", "X Speed"]},
      {"name":"Hyper Mind Continued", "moves":["Hyper Voice", "Calm Mind"],"items":["Wise Glasses", "Drive Lens", "Curse Incense", "X Speed"]},
      {"name":"Drain Fire", "moves":["Mystical Fire", "Draining Kiss"],"items":["Shell Bell", "Drive Lens", "Choice Specs", "Potion"]},
      {"name":"Drain Fire (Continued)", "moves":["Mystical Fire", "Draining Kiss"],"items":["Shell Bell", "Drive Lens", "Choice Specs", "X Speed"]}] },

  { n:"Typhlosion", r:"Attacker", id:157, wr:50, pr:7.4, br:2.3,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Flame Eruption (Damage)", "moves":["Flame Wheel", "Eruption"],"items":["Sp. Atk Specs", "Wise Glasses", "Slick Spoon", "Eject Button"]},
      {"name":"Flame Eruption (CDR)", "moves":["Flame Wheel", "Eruption"],"items":["Energy Amplifier", "Drive Lens", "Shell Bell", "Eject Button"]}] },

  { n:"Venusaur", r:"Attacker", id:3, wr:49.9, pr:17.5, br:1.7,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Sludge Beam", "moves":["Sludge Bomb", "Solar Beam"],"items":["Energy Amplifier", "Slick Spoon", "Curse Incense", "Eject Button"]},
      {"name":"Giga Dance", "moves":["Giga Drain", "Petal Dance"],"items":["Slick Spoon", "Drive Lens", "Shell Bell", "Full Heal"]},
      {"name":"Giga Beam", "moves":["Giga Drain", "Solar Beam"],"items":["Energy Amplifier", "Slick Spoon", "Drive Lens", "Eject Button"]}] },

  { n:"Yveltal", r:"Attacker", id:717, wr:48.4, pr:11.6, br:12.3,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Oblivion Pulse", "moves":["Oblivion Wing", "Dark Pulse"],"items":["Drive Lens", "Slick Spoon", "Wise Glasses", "Eject Button"]}] },

  { n:"Zapdos", r:"Attacker", id:145, wr:50, pr:10.5, br:4.5,
    strong:["Snorlax","Blastoise","Crustle"], weak:["Zeraora","Absol","Talonflame"],
    builds:[{"name":"Bolt Cannon", "moves":["Thunderbolt", "Zap Cannon"],"items":["Energy Amplifier", "Drive Lens", "Wise Glasses", "Eject Button"]}] },

  /* ============ DEFENDERS ============ */
  { n:"Articuno", r:"Defender", id:144, wr:49.8, pr:10.6, br:3.6,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Blizzard Beam", "moves":["Blizzard", "Ice Beam"],"items":["Resonant Guard", "Vanguard Bell", "Curse Incense", "X Speed"]}] },

  { n:"Blastoise", r:"Defender", id:9, wr:50.9, pr:25.3, br:16.8,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Surf Pump", "moves":["Hydro Pump", "Surf"],"items":["Focus Band", "Energy Amplifier", "Resonant Guard", "Eject Button"]},
      {"name":"Pump Spin (Bulk Emblems or none)", "moves":["Hydro Pump", "Rapid Spin"],"items":["Muscle Band", "Slick Spoon", "Focus Band", "Eject Button"]},
      {"name":"Pump Spin (CDR Emblems)", "moves":["Hydro Pump", "Rapid Spin"],"items":["Muscle Band", "Energy Amplifier", "Slick Spoon", "Eject Button"]},
      {"name":"Surf Pump", "moves":["Hydro Pump", "Surf"],"items":["Energy Amplifier", "Shell Bell", "Drive Lens", "Eject Button"]}] },

  { n:"Crustle", r:"Defender", id:558, wr:51, pr:14.4, br:0.7,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Scissor Tomb", "moves":["Rock Tomb", "X-Scissor"],"items":["Resonant Guard", "Focus Band", "Exp Share", "Eject Button"]},
      {"name":"Rocks", "moves":["Rock Tomb", "Stealth Rock"],"items":["Resonant Guard", "Focus Band", "Exp Share", "Eject Button"]},
      {"name":"Scissor Smash", "moves":["Shell Smash", "X-Scissor"],"items":["Accel Bracer", "Rocky Helmet", "Razor Claw", "Eject Button"]}] },

  { n:"Goodra", r:"Defender", id:706, wr:48.6, pr:5.5, br:0.6,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Muddy Water", "moves":["Muddy Water"],"items":["Slick Spoon", "Muscle Band", "Resonant Guard", "X Speed"]},
      {"name":"Dragon Pulse", "moves":["Dragon Pulse"],"items":["Slick Spoon", "Muscle Band", "Resonant Guard", "X Speed"]}] },

  { n:"Greedent", r:"Defender", id:820, wr:51.9, pr:2.7, br:0.3,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Covet Belch", "moves":["Covet", "Belch"],"items":["Attack Weight", "Weakness Policy", "Focus Band", "Eject Button"]},
      {"name":"Score Squirrel", "moves":["Covet", "Belch"],"items":["Attack Weight", "Weakness Policy", "Focus Band", "Potion"]},
      {"name":"Bullet Stuff", "moves":["Stuff Cheeks", "Bullet Seed"],"items":["Attack Weight", "Weakness Policy", "Focus Band", "Potion"]}] },

  { n:"Ho-Oh", r:"Defender", id:250, wr:49.7, pr:3.5, br:0.4,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Sky Spin", "moves":["Sky Attack", "Fire Spin"],"items":["Resonant Guard", "Curse Bangle", "Exp Share", "Full Heal"]},
      {"name":"Sky Spin", "moves":["Sky Attack", "Fire Spin"],"items":["Attack Weight", "Curse Bangle", "Weakness Policy", "Full Heal"]},
      {"name":"Flame Spin", "moves":["Flamethrower", "Fire Spin"],"items":["Resonant Guard", "Curse Bangle", "Exp Share", "Full Heal"]},
      {"name":"Sky Fire", "moves":["Sky Attack", "Sacred Fire"],"items":["Attack Weight", "Curse Bangle", "Weakness Policy", "Full Heal"]},
      {"name":"Flame Fire", "moves":["Flamethrower", "Sacred Fire"],"items":["Attack Weight", "Curse Bangle", "Weakness Policy", "Full Heal"]}] },

  { n:"Lapras", r:"Defender", id:131, wr:50.1, pr:14.6, br:0.9,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Water Pulse + Any (Damage)", "moves":["Water Pulse"],"items":["Slick Spoon", "Curse Incense", "Sp. Atk Specs", "X Speed"]},
      {"name":"Water Pulse + Any (Utility)", "moves":["Water Pulse"],"items":["Curse Incense", "Resonant Guard", "Focus Band", "X Speed"]},
      {"name":"Perish Song (Damage)", "moves":["Perish Song"],"items":["Sp. Atk Specs", "Slick Spoon", "Drive Lens", "X Speed"]}] },

  { n:"Mamoswine", r:"Defender", id:473, wr:49.8, pr:17.1, br:1.3,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Ice Quake", "moves":["Ice Fang", "Earthquake"],"items":["Focus Band", "Resonant Guard", "Exp Share", "Eject Button"]},
      {"name":"Icicle Quake", "moves":["Icicle Crash", "Earthquake"],"items":["Focus Band", "Resonant Guard", "Exp Share", "Eject Button"]},
      {"name":"Icicle Horsepower", "moves":["Icicle Crash", "High Horsepower"],"items":["Focus Band", "Resonant Guard", "Exp Share", "Eject Button"]}] },

  { n:"Slowbro", r:"Defender", id:80, wr:48.6, pr:12, br:3.2,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Surf ???", "moves":["Surf", "Amnesia"],"items":["Exp Share", "Resonant Guard", "Focus Band", "Eject Button"]},
      {"name":"Tele Surf", "moves":["Surf", "Telekinesis"],"items":["Exp Share", "Resonant Guard", "Focus Band", "Eject Button"]},
      {"name":"Scald ???", "moves":["Scald", "Amnesia"],"items":["Exp Share", "Resonant Guard", "Focus Band", "Eject Button"]},
      {"name":"Attacker Bro", "moves":["Scald", "Amnesia"],"items":["Curse Incense", "Slick Spoon", "Choice Specs", "Eject Button"]}] },

  { n:"Snorlax", r:"Defender", id:143, wr:50.1, pr:21.5, br:3.5,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Heavy Block", "moves":["Heavy Slam", "Block"],"items":["Exp Share", "Resonant Guard", "Buddy Barrier", "Eject Button"]},
      {"name":"Heavy Yawn", "moves":["Heavy Slam", "Yawn"],"items":["Exp Share", "Resonant Guard", "Focus Band", "Eject Button"]},
      {"name":"Flail Block", "moves":["Flail", "Block"],"items":["Aeos Cookie", "Big Root", "Resonant Guard", "X Speed"]},
      {"name":"Flail Yawn", "moves":["Flail", "Yawn"],"items":["Aeos Cookie", "Rapid Fire Scarf", "Focus Band", "X Speed"]}] },

  { n:"Trevenant", r:"Defender", id:709, wr:49.9, pr:11.6, br:0.7,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Wood Hammer", "moves":["Wood Hammer"],"items":["Focus Band", "Resonant Guard", "Exp Share", "Eject Button"]},
      {"name":"Curse (Protector)", "moves":["Curse"],"items":["Focus Band", "Resonant Guard", "Exp Share", "X Speed"]},
      {"name":"Curse (Threaten)", "moves":["Curse"],"items":["Focus Band", "Big Root", "Curse Bangle", "Eject Button"]}] },

  { n:"Umbreon", r:"Defender", id:197, wr:49, pr:18, br:5.3,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Foul Snarl (PLEASE READ DESCRIPTION)", "moves":["Foul Play", "Snarl"],"items":["Resonant Guard", "Focus Band", "Buddy Barrier", "Eject Button"]},
      {"name":"Mean Wish (PLEASE READ DESCRIPTION)", "moves":["Mean Look", "Wish"],"items":["Resonant Guard", "Buddy Barrier", "Attack Weight", "Eject Button"]},
      {"name":"Foul Wish (PLEASE READ DESCRIPTION)", "moves":["Foul Play", "Wish"],"items":["Resonant Guard", "Buddy Barrier", "Attack Weight", "Eject Button"]},
      {"name":"Mean Snarl (PLEASE READ DESCRIPTION)", "moves":["Mean Look", "Snarl"],"items":["Resonant Guard", "Focus Band", "Buddy Barrier", "Eject Button"]}] },

  { n:"Vaporeon", r:"Defender", id:134, wr:49.9, pr:10, br:0.8,
    strong:["Greninja","Cinderace","Pikachu"], weak:["Lucario","Urshifu","Zacian"],
    builds:[{"name":"Muddy Turn (Supportive)", "moves":["Muddy Water", "Flip Turn"],"items":["Resonant Guard", "Curse Incense", "Buddy Barrier", "Eject Button"]},
      {"name":"Hydro Turn", "moves":["Hydro Pump", "Flip Turn"],"items":["Resonant Guard", "Curse Incense", "Buddy Barrier", "Eject Button"]},
      {"name":"Muddy Turn (Damage)", "moves":["Muddy Water", "Flip Turn"],"items":["Sp. Atk Specs", "Curse Incense", "Drive Lens", "Eject Button"]},
      {"name":"Flip Splash", "moves":["Muddy Water", "Flip Turn"],"items":["Energy Amplifier", "Buddy Barrier", "Resonant Guard", "Eject Button"]},
      {"name":"Hydro Ring", "moves":["Hydro Pump", "Aqua Ring"],"items":["Sp. Atk Specs", "Drive Lens", "Wise Glasses", "Eject Button"]}] },

  /* ============ ALL-ROUNDERS ============ */
  { n:"Aegislash", r:"All-Rounder", id:681, wr:48.6, pr:6.7, br:0.3,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Sacred Guard", "moves":["Sacred Sword", "Wide Guard"],"items":["Attack Weight", "Weakness Policy", "Charging Charm", "Full Heal"]},
      {"name":"Iron Claw", "moves":["Shadow Claw", "Iron Head"],"items":["Attack Weight", "Razor Claw", "Weakness Policy", "Full Heal"]},
      {"name":"Shadow Guard", "moves":["Shadow Claw", "Wide Guard"],"items":["Attack Weight", "Razor Claw", "Weakness Policy", "Full Heal"]},
      {"name":"Iron Claw", "moves":["Shadow Claw", "Iron Head"],"items":["Attack Weight", "Razor Claw", "Scope Lens", "Full Heal"]}] },

  { n:"Azumarill", r:"All-Rounder", id:184, wr:49.8, pr:9.3, br:0.5,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Aqua Pulse", "moves":["Aqua Tail", "Water Pulse"],"items":["Attack Weight", "Scope Lens", "Accel Bracer", "X Speed"]},
      {"name":"Pool Play", "moves":["Whirlpool", "Play Rough"],"items":["Attack Weight", "Accel Bracer", "Scope Lens", "X Speed"]},
      {"name":"Whirl Pulse", "moves":["Whirlpool", "Water Pulse"],"items":["Attack Weight", "Weakness Policy", "Scope Lens", "X Speed"]}] },

  { n:"Blaziken", r:"All-Rounder", id:257, wr:51.1, pr:8.8, br:0.5,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Chicken & Waffles", "moves":["Aerial Ace", "Ember"],"items":["Attack Weight", "Aeos Cookie", "Weakness Policy", "Eject Button"]},
      {"name":"KFC 3 Piece Meal", "moves":[{},
      "Bulk Leaning Physical Standard"],"items":["Attack Weight", "Accel Bracer", "Razor Claw", "Eject Button"]}] },

  { n:"Buzzwole", r:"All-Rounder", id:794, wr:48.4, pr:19.6, br:7.4,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Super Smack", "moves":["Superpower", "Smack Down"],"items":["Attack Weight", "Weakness Policy", "Focus Band", "Eject Button"]},
      {"name":"Super Lunge", "moves":["Superpower", "Lunge"],"items":["Attack Weight", "Muscle Band", "Weakness Policy", "Eject Button"]},
      {"name":"Smack Life", "moves":["Leech Life", "Smack Down"],"items":["Accel Bracer", "Attack Weight", "Focus Band", "Eject Button"]},
      {"name":"Leech Lunge", "moves":["Leech Life", "Lunge"],"items":["Accel Bracer", "Attack Weight", "Focus Band", "Full Heal"]}] },

  { n:"Ceruledge", r:"All-Rounder", id:937, wr:50.8, pr:15.8, br:1.4,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Psycho Force", "moves":["Psycho Cut", "Phantom Force"],"items":["Muscle Band", "Razor Claw", "Curse Bangle", "Eject Button"]},
      {"name":"Psycho Charge", "moves":["Psycho Cut", "Flame Charge"],"items":["Muscle Band", "Razor Claw", "Curse Bangle", "Eject Button"]},
      {"name":"Bitter Force", "moves":["Bitter Blade", "Phantom Force"],"items":["Attack Weight", "Accel Bracer", "Razor Claw", "Eject Button"]},
      {"name":"Bitter Charge", "moves":["Bitter Blade", "Flame Charge"],"items":["Muscle Band", "Razor Claw", "Curse Bangle", "Eject Button"]}] },

  { n:"Charizard", r:"All-Rounder", id:6, wr:50.1, pr:4.1, br:0.5,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Flame Blitz", "moves":["Flamethrower", "Flare Blitz"],"items":["Scope Lens", "Attack Weight", "Accel Bracer", "X Speed"]},
      {"name":"Flame Blast", "moves":["Flamethrower", "Fire Blast"],"items":["Scope Lens", "Accel Bracer", "Attack Weight", "X Speed"]},
      {"name":"Fire Blitz", "moves":["Fire Punch", "Flare Blitz"],"items":["Scope Lens", "Accel Bracer", "Attack Weight", "Full Heal"]}] },

  { n:"Dhelmise", r:"All-Rounder", id:781, wr:48.9, pr:3.4, br:0.1,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Items Only", "moves":["Bulldoze", "Payback"],"items":["Attack Weight", "Resonant Guard", "Float Stone", "Eject Button"]}] },

  { n:"Dragonite", r:"All-Rounder", id:149, wr:51.2, pr:3.7, br:0.3,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Dragon Beam", "moves":["Dragon Dance", "Hyper Beam"],"items":["Muscle Band", "Scope Lens", "Razor Claw", "Full Heal"]},
      {"name":"Extreme Outrage", "moves":["Extreme Speed", "Outrage"],"items":["Rapid Fire Scarf", "Focus Band", "Choice Scarf", "Full Heal"]}] },

  { n:"Empoleon", r:"All-Rounder", id:395, wr:50.7, pr:4.9, br:0.3,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Aqua Cannon", "moves":["Aqua Jet", "Hydro Cannon"],"items":["Sp. Atk Specs", "Curse Incense", "Wise Glasses", "Full Heal"]},
      {"name":"Aqua Cannon (Heal Cycle)", "moves":["Aqua Jet", "Hydro Cannon"],"items":["Shell Bell", "Energy Amplifier", "Drive Lens", "Full Heal"]}] },

  { n:"Falinks", r:"All-Rounder", id:870, wr:52.8, pr:1.5, br:0.2,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"No Horny", "moves":["Megahorn", "No Retreat"],"items":["Attack Weight", "Accel Bracer", "Weakness Policy", "Full Heal"]},
      {"name":"No Head", "moves":["Iron Head", "No Retreat"],"items":["Attack Weight", "Accel Bracer", "Weakness Policy", "Full Heal"]},
      {"name":"Heads Up", "moves":["Iron Head", "Beat Up"],"items":["Attack Weight", "Accel Bracer", "Muscle Band", "Full Heal"]}] },

  { n:"Feraligatr", r:"All-Rounder", id:160, wr:48.9, pr:6.5, br:17.7,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Waterfall Crunch", "moves":["Crunch", "Waterfall"],"items":["Razor Claw", "Attack Weight", "Accel Bracer", "Full Heal"]}] },

  { n:"Garchomp", r:"All-Rounder", id:445, wr:51.9, pr:4.7, br:0.2,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Full Dragon", "moves":["Dragon Rush", "Dragon Claw"],"items":["Scope Lens", "Choice Scarf", "Rapid Fire Scarf", "Eject Button"]},
      {"name":"Full Dragon", "moves":["Dragon Rush", "Dragon Claw"],"items":["Scope Lens", "Muscle Band", "Focus Band", "Eject Button"]},
      {"name":"Earthquake Dig", "moves":["Dig", "Earthquake"],"items":["Scope Lens", "Rapid Fire Scarf", "Choice Scarf", "Potion"]},
      {"name":"Earthquake Dig", "moves":["Dig", "Earthquake"],"items":["Scope Lens", "Weakness Policy", "Energy Amplifier", "Potion"]}] },

  { n:"Gyarados", r:"All-Rounder", id:130, wr:51.5, pr:3, br:0.2,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Bounce Breath", "moves":["Dragon Breath", "Bounce"],"items":["Attack Weight", "Accel Bracer", "Energy Amplifier", "Eject Button"]},
      {"name":"Water Breath", "moves":["Dragon Breath", "Waterfall"],"items":["Attack Weight", "Accel Bracer", "Energy Amplifier", "Eject Button"]},
      {"name":"Aqua Bounce", "moves":["Aqua Tail", "Bounce"],"items":["Attack Weight", "Accel Bracer", "Energy Amplifier", "Eject Button"]}] },

  { n:"Lucario", r:"All-Rounder", id:448, wr:48.5, pr:8.2, br:0.5,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Power-Up Rush", "moves":["Power-Up Punch", "Bone Rush"],"items":["Attack Weight", "Weakness Policy", "Razor Claw", "Eject Button"]},
      {"name":"Extreme Rush", "moves":["Extreme Speed", "Bone Rush"],"items":["Attack Weight", "Weakness Policy", "Razor Claw", "Full Heal"]},
      {"name":"Power-Up Combat", "moves":["Power-Up Punch", "Close Combat"],"items":["Attack Weight", "Weakness Policy", "Accel Bracer", "Eject Button"]},
      {"name":"Power-Up Rush", "moves":["Power-Up Punch", "Bone Rush"],"items":["Attack Weight", "Accel Bracer", "Energy Amplifier", "Eject Button"]}] },

  { n:"Machamp", r:"All-Rounder", id:68, wr:51.2, pr:10.6, br:1.7,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Cross Punch", "moves":["Dynamic Punch", "Cross Chop"],"items":["Razor Claw", "Attack Weight", "Accel Bracer", "Eject Button"]},
      {"name":"Dynamic Combat", "moves":["Dynamic Punch", "Close Combat"],"items":["Accel Bracer", "Energy Amplifier", "Attack Weight", "Eject Button"]},
      {"name":"Cross Submission", "moves":["Submission", "Cross Chop"],"items":["Attack Weight", "Razor Claw", "Scope Lens", "Eject Button"]},
      {"name":"Submission Combat", "moves":["Submission", "Close Combat"],"items":["Accel Bracer", "Energy Amplifier", "Attack Weight", "Eject Button"]}] },

  { n:"Mega Charizard X", r:"All-Rounder", id:10034, wr:51.3, pr:11.2, br:10.4,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Fire Blitz", "moves":["Fire Punch", "Flare Blitz"],"items":["Charizardite X", "Scope Lens", "Attack Weight", "Full Heal"]}] },

  { n:"Mega Charizard Y", r:"All-Rounder", id:10035, wr:50.7, pr:3.6, br:2.7,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Flame Blast", "moves":["Flamethrower", "Fire Blast"],"items":["Charizardite Y", "Attack Weight", "Curse Bangle", "Full Heal"]}] },

  { n:"Mega Gyarados", r:"All-Rounder", id:10041, wr:49.6, pr:0.8, br:0.3,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Water Breath (Hyper offense)", "moves":["Dragon Breath", "Waterfall"],"items":["Gyaradosite", "Attack Weight", "Accel Bracer", "Eject Button"]},
      {"name":"Water Breath (Defensive Karp)", "moves":["Dragon Breath", "Waterfall"],"items":["Gyaradosite", "Attack Weight", "Focus Band", "Eject Button"]}] },

  { n:"Mega Lucario", r:"All-Rounder", id:10059, wr:50.6, pr:6.7, br:0.7,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Items Only", "moves":["Power-Up Punch", "Close Combat"],"items":["Lucarionite", "Attack Weight", "Weakness Policy", "Eject Button"]}] },

  { n:"Mega Mewtwo X", r:"All-Rounder", id:10043, wr:51.8, pr:10.4, br:0.7,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Future Recover", "moves":["Future Sight", "Recover"],"items":["Mewtwonite X", "Attack Weight", "Weakness Policy", "Full Heal"]},
      {"name":"Future Teleport", "moves":["Future Sight", "Teleport"],"items":["Mewtwonite X", "Attack Weight", "Weakness Policy", "Full Heal"]},
      {"name":"Psystrike Recover", "moves":["Psystrike", "Recover"],"items":["Mewtwonite X", "Attack Weight", "Weakness Policy", "Potion"]},
      {"name":"Psystrike Teleport", "moves":["Psystrike", "Teleport"],"items":["Mewtwonite X", "Attack Weight", "Weakness Policy", "Potion"]}] },

  { n:"Metagross", r:"All-Rounder", id:376, wr:51.6, pr:5.7, br:0.4,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Gyro Rise", "moves":["Gyro Ball", "Magnet Rise"],"items":["Attack Weight", "Accel Bracer", "Weakness Policy", "X Speed"]},
      {"name":"Gyro Zen", "moves":["Gyro Ball", "Zen Headbutt"],"items":["Attack Weight", "Accel Bracer", "Weakness Policy", "X Speed"]},
      {"name":"Meteor Zen", "moves":["Meteor Mash", "Zen Headbutt"],"items":["Attack Weight", "Accel Bracer", "Weakness Policy", "Eject Button"]}] },

  { n:"Mimikyu", r:"All-Rounder", id:778, wr:49.6, pr:11.6, br:2.8,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Shadows", "moves":["Shadow Claw", "Shadow Sneak"],"items":["Razor Claw", "Muscle Band", "Attack Weight", "Full Heal"]},
      {"name":"Sneaky Play", "moves":["Play Rough", "Shadow Sneak"],"items":["Attack Weight", "Accel Bracer", "Curse Bangle", "X Attack"]},
      {"name":"Trick Claw", "moves":["Shadow Claw", "Trick Room"],"items":["Razor Claw", "Muscle Band", "Accel Bracer", "Full Heal"]}] },

  { n:"Moltres", r:"All-Rounder", id:146, wr:47.4, pr:3.7, br:0.6,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Heat Attack", "moves":["Heat Wave", "Sky Attack"],"items":["Sp. Atk Specs", "Curse Incense", "Focus Band", "Full Heal"]}] },

  { n:"Palkia", r:"All-Rounder", id:484, wr:53.2, pr:9.6, br:3.5,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Aura Claw (Damage)", "moves":["Aura Sphere", "Dragon Claw"],"items":["Sp. Atk Specs", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Aura Claw (Bulk)", "moves":["Aura Sphere", "Dragon Claw"],"items":["Sp. Atk Specs", "Rocky Helmet", "Buddy Barrier", "Potion"]}] },

  { n:"Pawmot", r:"All-Rounder", id:923, wr:51.4, pr:5.6, br:0.6,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Items Only", "moves":[],"items":["Muscle Band", "Razor Claw", "Weakness Policy", "Eject Button"]}] },

  { n:"Quaquaval", r:"All-Rounder", id:914, wr:50.4, pr:6.1, br:0.5,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Liquidation Sweep", "moves":["Low Sweep", "Liquidation"],"items":["Attack Weight", "Aeos Cookie", "Weakness Policy", "Full Heal"]}] },

  { n:"Scizor", r:"All-Rounder", id:212, wr:50.2, pr:14.3, br:3.4,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Bullet Dance", "moves":["Bullet Punch", "Swords Dance"],"items":["Accel Bracer", "Attack Weight", "Energy Amplifier", "Full Heal"]},
      {"name":"Swords Punch", "moves":["Bullet Punch", "Swords Dance"],"items":["Accel Bracer", "Attack Weight", "Razor Claw", "Full Heal"]},
      {"name":"Bullet Hit", "moves":["Bullet Punch", "Double Hit"],"items":["Accel Bracer", "Attack Weight", "Energy Amplifier", "Full Heal"]},
      {"name":"Double Punch", "moves":["Bullet Punch", "Double Hit"],"items":["Accel Bracer", "Attack Weight", "Razor Claw", "Full Heal"]}] },

  { n:"Scyther", r:"All-Rounder", id:123, wr:50, pr:0, br:0,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Double Wingbeat", "moves":["Dual Wingbeat", "Double Hit"],"items":["Accel Bracer", "Attack Weight", "Energy Amplifier", "Full Heal"]},
      {"name":"Double Wingbeat", "moves":["Dual Wingbeat", "Double Hit"],"items":["Muscle Band", "Attack Weight", "Charging Charm", "Full Heal"]},
      {"name":"Double Wingbeat", "moves":["Dual Wingbeat", "Double Hit"],"items":["Muscle Band", "Razor Claw", "Accel Bracer", "Full Heal"]}] },

  { n:"Sirfetch'd", r:"All-Rounder", id:865, wr:50.2, pr:11.3, br:0.8,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Detect Blade", "moves":["Leaf Blade", "Detect"],"items":["Attack Weight", "Scope Lens", "Razor Claw", "Eject Button"]},
      {"name":"Detect Cutter", "moves":["Fury Cutter", "Detect"],"items":["Attack Weight", "Scope Lens", "Razor Claw", "Eject Button"]}] },

  { n:"Solgaleo", r:"All-Rounder", id:791, wr:45.6, pr:8.4, br:5,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[] },

  { n:"Suicune", r:"All-Rounder", id:245, wr:50, pr:15.2, br:5.6,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Whirl Pool (CDR emphasis)", "moves":["Whirlpool"],"items":["Drive Lens", "Shell Bell", "Energy Amplifier", "Full Heal"]},
      {"name":"Whirl Beam (Utility Oriented)", "moves":["Whirlpool", "Ice Beam"],"items":["Curse Incense", "Resonant Guard", "Buddy Barrier", "Full Heal"]},
      {"name":"Surf Wind (CDR)", "moves":["Surf", "Icy Wind"],"items":["Energy Amplifier", "Drive Lens", "Shell Bell", "Full Heal"]},
      {"name":"Surf Wind (Burst)", "moves":["Surf", "Icy Wind"],"items":["Energy Amplifier", "Choice Specs", "Curse Incense", "Full Heal"]}] },

  { n:"Tinkaton", r:"All-Rounder", id:959, wr:52, pr:3.7, br:0.2,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Smack Thief", "moves":["Thief", "Smack Down"],"items":["Attack Weight", "Float Stone", "Charging Charm", "Eject Button"]},
      {"name":"Ice Down", "moves":["Ice Hammer", "Smack Down"],"items":["Attack Weight", "Float Stone", "Resonant Guard", "Eject Button"]},
      {"name":"Hammer Time", "moves":["Ice Hammer", "Gigaton Hammer"],"items":["Attack Weight", "Razor Claw", "Focus Band", "Eject Button"]},
      {"name":"Gigaton Thief", "moves":["Thief", "Gigaton Hammer"],"items":["Attack Weight", "Focus Band", "Aeos Cookie", "Eject Button"]}] },

  { n:"Tsareena", r:"All-Rounder", id:763, wr:50.1, pr:7.5, br:0.4,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Stomp (Part 1)", "moves":["Stomp"],"items":["Attack Weight", "Razor Claw", "Weakness Policy", "Full Heal"]},
      {"name":"Stomp (Part 2)", "moves":["Stomp"],"items":["Attack Weight", "Rapid Fire Scarf", "Aeos Cookie", "Full Heal"]},
      {"name":"Triple Axel", "moves":["Triple Axel"],"items":["Attack Weight", "Weakness Policy", "Accel Bracer", "Full Heal"]}] },

  { n:"Tyranitar", r:"All-Rounder", id:248, wr:51.9, pr:2.4, br:0.2,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Dark Tomb", "moves":["Dark Pulse", "Sand Tomb"],"items":["Attack Weight", "Muscle Band", "Focus Band", "Eject Button"]},
      {"name":"Ancient Pulse", "moves":["Dark Pulse", "Ancient Power"],"items":["Attack Weight", "Muscle Band", "Weakness Policy", "Eject Button"]},
      {"name":"Sand Stone", "moves":["Stone Edge", "Sand Tomb"],"items":["Muscle Band", "Razor Claw", "Focus Band", "Eject Button"]}] },

  { n:"Urshifu", r:"All-Rounder", id:892, wr:50.8, pr:10.2, br:11.7,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Rapid Strike Style", "moves":["Surging Strikes", "Liquidation"],"items":["Muscle Band", "Accel Bracer", "Razor Claw", "Full Heal"]},
      {"name":"Single Strike Style", "moves":["Wicked Blow", "Throat Chop"],"items":["Muscle Band", "Attack Weight", "Razor Claw", "Eject Button"]}] },

  { n:"Zacian", r:"All-Rounder", id:888, wr:49.8, pr:7.6, br:3.8,
    strong:["Blissey","Eldegoss","Comfey"], weak:["Greninja","Cinderace","Pikachu"],
    builds:[{"name":"Metal Rough", "moves":["Metal Claw", "Play Rough"],"items":["Rusted Sword", "Muscle Band", "Rapid Fire Scarf", "Full Heal"]},
      {"name":"Sacred Rough", "moves":["Sacred Sword", "Play Rough"],"items":["Rusted Sword", "Muscle Band", "Charging Charm", "Eject Button"]},
      {"name":"Metal Agility", "moves":["Metal Claw", "Agility"],"items":["Rusted Sword", "Muscle Band", "Rapid Fire Scarf", "Full Heal"]}] },

  /* ============ SPEEDSTERS ============ */
  { n:"Absol", r:"Speedster", id:359, wr:50.1, pr:11.8, br:1.3,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Pursuit Punch", "moves":["Pursuit", "Sucker Punch"],"items":["Razor Claw", "Scope Lens", "Accel Bracer", "Full Heal"]},
      {"name":"Night Cut", "moves":["Night Slash", "Psycho Cut"],"items":["Scope Lens", "Razor Claw", "Accel Bracer", "Full Heal"]},
      {"name":"Psycho Pursuit", "moves":["Pursuit", "Psycho Cut"],"items":["Razor Claw", "Scope Lens", "Accel Bracer", "Full Heal"]},
      {"name":"Night Punch", "moves":["Night Slash", "Sucker Punch"],"items":["Razor Claw", "Scope Lens", "Accel Bracer", "Full Heal"]}] },

  { n:"Darkrai", r:"Speedster", id:491, wr:50.3, pr:6, br:1.9,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Dark Plot (Opportunity Burst)", "moves":["Dark Void", "Nasty Plot"],"items":["Slick Spoon", "Drive Lens", "Wise Glasses", "Potion"]},
      {"name":"Dark Plot (CDR)", "moves":["Dark Void", "Nasty Plot"],"items":["Drive Lens", "Shell Bell", "Energy Amplifier", "Full Heal"]},
      {"name":"Dark Dark", "moves":["Dark Void", "Dark Pulse"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]},
      {"name":"Shadow Pulse", "moves":["Shadow Claw", "Dark Pulse"],"items":["Slick Spoon", "Wise Glasses", "Drive Lens", "Eject Button"]}] },

  { n:"Dodrio", r:"Speedster", id:85, wr:49.5, pr:7.9, br:9.4,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Tri Jump", "moves":["Tri Attack", "Jump Kick"],"items":["Attack Weight", "Razor Claw", "Charging Charm", "Full Heal"]},
      {"name":"Drill Kick", "moves":["Drill Peck", "Jump Kick"],"items":["Attack Weight", "Accel Bracer", "Charging Charm", "Full Heal"]},
      {"name":"Agility Attack", "moves":["Tri Attack", "Agility"],"items":["Attack Weight", "Accel Bracer", "Razor Claw", "Full Heal"]}] },

  { n:"Gengar", r:"Speedster", id:94, wr:51.3, pr:8.8, br:3.3,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Shadow Eater", "moves":["Dream Eater", "Shadow Ball"],"items":["Wise Glasses", "Drive Lens", "Choice Specs", "Eject Button"]},
      {"name":"Sludge Hex", "moves":["Hex", "Sludge Bomb"],"items":["Drive Lens", "Wise Glasses", "Sp. Atk Specs", "Full Heal"]}] },

  { n:"Leafeon", r:"Speedster", id:470, wr:46.9, pr:8.3, br:0.8,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Razor Ace", "moves":["Razor Leaf", "Aerial Ace"],"items":["Razor Claw", "Energy Amplifier", "Attack Weight", "X Attack"]},
      {"name":"Solar Leaf", "moves":["Solar Blade", "Leaf Blade"],"items":["Attack Weight", "Energy Amplifier", "Accel Bracer", "Eject Button"]}] },

  { n:"Meowscarada", r:"Speedster", id:908, wr:49.2, pr:6.4, br:0.7,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Double Trick", "moves":["Flower Trick", "Double Team"],"items":["Razor Claw", "Energy Amplifier", "Accel Bracer", "Eject Button"]},
      {"name":"Double Trick", "moves":["Flower Trick", "Double Team"],"items":["Attack Weight", "Energy Amplifier", "Razor Claw", "Eject Button"]},
      {"name":"Night Blaze", "moves":["Night Slash", "Trailblaze"],"items":["Scope Lens", "Razor Claw", "Attack Weight", "Eject Button"]},
      {"name":"Flower Blaze", "moves":["Flower Trick", "Trailblaze"],"items":["Attack Weight", "Accel Bracer", "Energy Amplifier", "Eject Button"]}] },

  { n:"Meowth", r:"Speedster", id:52, wr:49.8, pr:9.9, br:9.2,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Fury Attack", "moves":["Fury Swipes", "Feint Attack"],"items":["Attack Weight", "Razor Claw", "Accel Bracer", "Full Heal"]},
      {"name":"Fury Assurance", "moves":["Fury Swipes", "Assurance"],"items":["Attack Weight", "Muscle Band", "Razor Claw", "Full Heal"]},
      {"name":"Fury Assurance", "moves":["Fury Swipes", "Assurance"],"items":["Attack Weight", "Accel Bracer", "Energy Amplifier", "Full Heal"]},
      {"name":"Pay Attack", "moves":["Pay Day", "Feint Attack"],"items":["Attack Weight", "Accel Bracer", "Energy Amplifier", "Eject Button"]}] },

  { n:"Morpeko", r:"Speedster", id:877, wr:50, pr:0, br:0,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[] },

  { n:"Rapidash", r:"Speedster", id:78, wr:51.9, pr:5, br:0.7,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Dazzling Strike", "moves":["Dazzling Gleam", "Smart Strike"],"items":["Wise Glasses", "Shell Bell", "Sp. Atk Specs", "Full Heal"]},
      {"name":"Agility Wind", "moves":["Fairy Wind", "Agility"],"items":["Wise Glasses", "Shell Bell", "Sp. Atk Specs", "Full Heal"]},
      {"name":"Smart Wind", "moves":["Fairy Wind", "Smart Strike"],"items":["Wise Glasses", "Shell Bell", "Sp. Atk Specs", "Full Heal"]}] },

  { n:"Talonflame", r:"Speedster", id:663, wr:49.5, pr:16, br:2.6,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Brave Ace", "moves":["Aerial Ace", "Brave Bird"],"items":["Attack Weight", "Razor Claw", "Charging Charm", "Eject Button"]},
      {"name":"Fly Charge", "moves":["Flame Charge", "Fly"],"items":["Attack Weight", "Charging Charm", "Razor Claw", "Eject Button"]}] },

  { n:"Zeraora", r:"Speedster", id:807, wr:49, pr:12.4, br:2.5,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Spark Charge", "moves":["Spark", "Wild Charge"],"items":["Weakness Policy", "Razor Claw", "Accel Bracer", "X Attack"]},
      {"name":"Discharge Switch", "moves":["Volt Switch", "Discharge"],"items":["Weakness Policy", "Razor Claw", "Accel Bracer", "Full Heal"]},
      {"name":"Spark Discharge", "moves":["Spark", "Discharge"],"items":["Weakness Policy", "Razor Claw", "Buddy Barrier", "X Attack"]},
      {"name":"Spark Discharge", "moves":["Spark", "Discharge"],"items":["Weakness Policy", "Razor Claw", "Accel Bracer", "X Attack"]},
      {"name":"Discharge Switch", "moves":["Volt Switch", "Discharge"],"items":["Accel Bracer", "Energy Amplifier", "Charging Charm", "Full Heal"]}] },

  { n:"Zoroark", r:"Speedster", id:571, wr:49.3, pr:15.8, br:10.1,
    strong:["Greninja","Cinderace","Decidueye"], weak:["Snorlax","Slowbro","Umbreon"],
    builds:[{"name":"Feint Claw", "moves":["Feint Attack", "Shadow Claw"],"items":["Attack Weight", "Weakness Policy", "Accel Bracer", "Full Heal"]},
      {"name":"Night Cut", "moves":["Night Slash", "Cut"],"items":["Attack Weight", "Weakness Policy", "Razor Claw", "Full Heal"]}] },

  /* ============ SUPPORTERS ============ */
  { n:"Alcremie", r:"Supporter", id:869, wr:48.2, pr:4.2, br:0.2,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Decorating Gleam", "moves":["Decorate", "Dazzling Gleam"],"items":["Exp Share", "Buddy Barrier", "Wise Glasses", "Eject Button"]},
      {"name":"Recovery Scent", "moves":["Recover", "Sweet Scent"],"items":["Exp Share", "Buddy Barrier", "Rescue Hood", "Eject Button"]},
      {"name":"Decorating Scent", "moves":["Decorate", "Sweet Scent"],"items":["Exp Share", "Buddy Barrier", "Wise Glasses", "Eject Button"]}] },

  { n:"Blissey", r:"Supporter", id:242, wr:49.8, pr:13.4, br:6.8,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Soft Bomb", "moves":["Soft-Boiled", "Egg Bomb"],"items":["Exp Share", "Buddy Barrier", "Energy Amplifier", "X Speed"]},
      {"name":"Safe Egg", "moves":["Safeguard", "Egg Bomb"],"items":["Exp Share", "Buddy Barrier", "Energy Amplifier", "X Speed"]},
      {"name":"Helping Guard", "moves":["Safeguard", "Helping Hand"],"items":["Exp Share", "Buddy Barrier", "Energy Amplifier", "X Speed"]}] },

  { n:"Clefable", r:"Supporter", id:36, wr:48.7, pr:10.3, br:11.6,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Moonlight+Any", "moves":["Moonlight"],"items":["Exp Share", "Sp. Atk Specs", "Buddy Barrier", "X Speed"]},
      {"name":"Kiss Me", "moves":["Draining Kiss", "Follow Me"],"items":["Drive Lens", "Shell Bell", "Energy Amplifier", "Eject Button"]}] },

  { n:"Comfey", r:"Supporter", id:764, wr:45, pr:11.5, br:18.6,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Floral Knot", "moves":["Floral Healing", "Grass Knot"],"items":["Buddy Barrier", "Resonant Guard", "Exp Share", "Slow Smoke"]},
      {"name":"Floral Knot", "moves":["Floral Healing", "Grass Knot"],"items":["Exp Share", "Buddy Barrier", "Drive Lens", "Slow Smoke"]},
      {"name":"Floral Leaf", "moves":["Floral Healing", "Magical Leaf"],"items":["Exp Share", "Buddy Barrier", "Drive Lens", "Slow Smoke"]},
      {"name":"Sweet Knot", "moves":["Sweet Kiss", "Grass Knot"],"items":["Exp Share", "Buddy Barrier", "Resonant Guard", "Slow Smoke"]}] },

  { n:"Eldegoss", r:"Supporter", id:830, wr:50.5, pr:8.8, br:0.3,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Pollen Spore", "moves":["Pollen Puff", "Cotton Spore"],"items":["Buddy Barrier", "Resonant Guard", "Muscle Band", "X Speed"]},
      {"name":"Pollen Guard", "moves":["Pollen Puff", "Cotton Guard"],"items":["Buddy Barrier", "Resonant Guard", "Muscle Band", "X Speed"]},
      {"name":"Pollen Guard", "moves":["Pollen Puff", "Cotton Guard"],"items":["Buddy Barrier", "Resonant Guard", "Rescue Hood", "X Speed"]},
      {"name":"Tornado Guard", "moves":["Leaf Tornado", "Cotton Guard"],"items":["Muscle Band", "Curse Incense", "Buddy Barrier", "Eject Button"]},
      {"name":"Tornado Spore", "moves":["Leaf Tornado", "Cotton Spore"],"items":["Muscle Band", "Curse Incense", "Buddy Barrier", "Eject Button"]}] },

  { n:"Hoopa", r:"Supporter", id:720, wr:49.6, pr:5.8, br:0.3,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Hyperspace Force (Item Options: READ DESCRIPTION)", "moves":["Hyperspace Hole", "Phantom Force"],"items":["Resonant Guard", "Muscle Band", "Exp Share", "Full Heal"]},
      {"name":"Shadow Trick (Item options: READ DESCRIPTION)", "moves":["Trick", "Shadow Ball"],"items":["Muscle Band", "Resonant Guard", "Exp Share", "Full Heal"]},
      {"name":"Phantom Trick (Item options: READ DESCRIPTION)", "moves":["Trick", "Phantom Force"],"items":["Resonant Guard", "Muscle Band", "Exp Share", "Full Heal"]},
      {"name":"Phantom Trick", "moves":["Trick", "Phantom Force"],"items":["Shell Bell", "Rescue Hood", "Energy Amplifier", "Full Heal"]}] },

  { n:"Latias", r:"Supporter", id:380, wr:51.4, pr:9.7, br:0.4,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Mist Pulse", "moves":["Dragon Pulse", "Mist Ball"],"items":["Shell Bell", "Curse Incense", "Drive Lens", "Potion"]},
      {"name":"Mist Breath", "moves":["Dragon Breath", "Mist Ball"],"items":["Curse Incense", "Shell Bell", "Drive Lens", "Potion"]},
      {"name":"Cheer Breath", "moves":["Dragon Breath", "Dragon Cheer"],"items":["Shell Bell", "Exp Share", "Resonant Guard", "Potion"]},
      {"name":"Cheer Pulse", "moves":["Dragon Pulse", "Dragon Cheer"],"items":["Drive Lens", "Sp. Atk Specs", "Resonant Guard", "Potion"]}] },

  { n:"Meganium", r:"Supporter", id:154, wr:50.9, pr:4.4, br:0.5,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Grass Blizzard", "moves":["Grass Knot", "Petal Blizzard"],"items":["Buddy Barrier", "Sp. Atk Specs", "Resonant Guard", "X Speed"]}] },

  { n:"Mr. Mime", r:"Supporter", id:122, wr:51.7, pr:7, br:0.7,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Confusion Barrier", "moves":["Confusion", "Barrier"],"items":["Resonant Guard", "Focus Band", "Exp Share", "Eject Button"]},
      {"name":"Psychic Swap", "moves":["Psychic", "Power Swap"],"items":["Resonant Guard", "Sp. Atk Specs", "Exp Share", "Eject Button"]},
      {"name":"Confusion Swap", "moves":["Confusion", "Power Swap"],"items":["Resonant Guard", "Slick Spoon", "Exp Share", "Eject Button"]},
      {"name":"Psychic Barrier", "moves":["Psychic", "Barrier"],"items":["Resonant Guard", "Sp. Atk Specs", "Exp Share", "Eject Button"]}] },

  { n:"Psyduck", r:"Supporter", id:54, wr:50.2, pr:14.9, br:7.1,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Surf - READ EXPLANATION; Items - HP emphasis", "moves":["Surf"],"items":["Resonant Guard", "Buddy Barrier", "Exp Share", "Potion"]},
      {"name":"Bubble Beam- READ EXPLANATION", "moves":["Bubble Beam"],"items":["Exp Share", "Curse Incense", "Shell Bell", "Potion"]},
      {"name":"Disable- READ EXPLANATION", "moves":["Surf", "Disable"],"items":["Exp Share", "Resonant Guard", "Buddy Barrier", "Potion"]},
      {"name":"Psychic- READ EXPLANATION", "moves":["Bubble Beam", "Psychic"],"items":["Exp Share", "Curse Incense", "Shell Bell", "Potion"]}] },

  { n:"Sableye", r:"Supporter", id:302, wr:46.5, pr:6.2, br:3.3,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Confuse Knock", "moves":["Knock Off", "Confuse Ray"],"items":["Float Stone", "Resonant Guard", "Exp Share", "Eject Button"]},
      {"name":"Shadow Ray", "moves":["Shadow Sneak", "Confuse Ray"],"items":["Float Stone", "Resonant Guard", "Exp Share", "Full Heal"]},
      {"name":"Feint Off", "moves":["Knock Off", "Feint Attack"],"items":["Float Stone", "Curse Bangle", "Exp Share", "Eject Button"]},
      {"name":"Sneak Attack", "moves":["Shadow Sneak", "Feint Attack"],"items":["Float Stone", "Curse Bangle", "Exp Share", "Full Heal"]}] },

  { n:"Wigglytuff", r:"Supporter", id:40, wr:50.3, pr:7, br:2,
    strong:["Machamp","Buzzwole","Tyranitar"], weak:["Greninja","Cinderace","Talonflame"],
    builds:[{"name":"Dazzling Song (Disruptor)", "moves":["Sing", "Dazzling Gleam"],"items":["Focus Band", "Resonant Guard", "Muscle Band", "Eject Button"]},
      {"name":"Dazzling Song (Protector)", "moves":["Sing", "Dazzling Gleam"],"items":["Resonant Guard", "Exp Share", "Focus Band", "Eject Button"]},
      {"name":"Roll Slap", "moves":["Rollout", "Double Slap"],"items":["Resonant Guard", "Focus Band", "Buddy Barrier", "Eject Button"]}] },

];
